# Generated by Django 5.2.16 on 2026-07-23 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('normalized_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_services_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_services_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'code'),
                'permissions': (('change_service_price', 'Can change service price'), ('deactivate_service', 'Can deactivate service'), ('reactivate_service', 'Can reactivate service')),
            },
        ),
        migrations.CreateModel(
            name='ServiceApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_category', models.CharField(choices=[('SMALL', 'Small vehicle'), ('COMMERCIAL', 'Commercial vehicle'), ('HEAVY', 'Heavy vehicle')], max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicabilities', to='service_catalogue.service')),
            ],
            options={
                'ordering': ('service', 'vehicle_category'),
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_price_changes', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='service_catalogue.service')),
            ],
            options={
                'ordering': ('-effective_from', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'name'], name='svc_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceapplicability',
            index=models.Index(fields=['vehicle_category', 'service'], name='svc_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceapplicability',
            constraint=models.UniqueConstraint(fields=('service', 'vehicle_category'), name='svc_unique_category'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_until__isnull', True)), fields=('service',), name='svc_one_current_price'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='svc_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='svc_price_valid_period'),
        ),
    ]
