# Generated by Django 5.2.16 on 2026-07-23 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name_snapshot', models.CharField(editable=False, max_length=200)),
                ('customer_phone_snapshot', models.CharField(blank=True, editable=False, max_length=30)),
                ('customer_email_snapshot', models.EmailField(blank=True, editable=False, max_length=254)),
                ('vehicle_registration_snapshot', models.CharField(editable=False, max_length=40)),
                ('vehicle_make_snapshot', models.CharField(editable=False, max_length=100)),
                ('vehicle_model_snapshot', models.CharField(editable=False, max_length=100)),
                ('vehicle_year_snapshot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('vehicle_color_snapshot', models.CharField(blank=True, editable=False, max_length=50)),
                ('arrival_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('arrival_mileage', models.PositiveIntegerField()),
                ('customer_complaint', models.TextField()),
                ('visible_condition', models.TextField(blank=True)),
                ('fuel_level', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('EMPTY', 'Empty'), ('QUARTER', 'Quarter'), ('HALF', 'Half'), ('THREE_QUARTERS', 'Three quarters'), ('FULL', 'Full')], default='UNKNOWN', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INSPECTED', 'Inspected'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-arrival_at', '-created_at'),
                'permissions': (('cancel_jobcard', 'Can cancel job card'),),
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_type', models.CharField(choices=[('INITIAL', 'Initial inspection'), ('DIAGNOSTIC', 'Diagnostic inspection'), ('SAFETY', 'Safety inspection'), ('QUALITY_CONTROL', 'Quality-control inspection')], default='INITIAL', max_length=30)),
                ('findings', models.TextField()),
                ('safety_observations', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_inspections', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='jobs.jobcard')),
            ],
            options={
                'ordering': ('-inspected_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='JobNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('GENERAL', 'General'), ('CUSTOMER_COMMUNICATION', 'Customer communication'), ('INTERNAL', 'Internal'), ('CANCELLATION', 'Cancellation')], default='GENERAL', max_length=30)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_notes_created', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='jobs.jobcard')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['status', 'arrival_at'], name='jobs_status_arrival_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['customer', 'status'], name='jobs_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['vehicle', 'status'], name='jobs_vehicle_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcard',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('OPEN', 'INSPECTED'))), fields=('vehicle',), name='jobs_one_active_vehicle'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['job_card', 'inspected_at'], name='jobs_inspection_date_idx'),
        ),
        migrations.AddIndex(
            model_name='jobnote',
            index=models.Index(fields=['job_card', 'created_at'], name='jobs_note_date_idx'),
        ),
    ]
