# Generated by Django 5.2.16 on 2026-07-26 21:26

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INSPECTED', 'Inspected'), ('RELEASED', 'Vehicle released'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('released_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('final_mileage', models.PositiveBigIntegerField()),
                ('final_condition', models.TextField()),
                ('received_by_name', models.CharField(max_length=200)),
                ('received_by_contact', models.CharField(blank=True, max_length=100)),
                ('handover_notes', models.TextField(blank=True)),
                ('invoice_number_snapshot', models.CharField(editable=False, max_length=30)),
                ('invoice_status_snapshot', models.CharField(editable=False, max_length=30)),
                ('invoice_currency_snapshot', models.CharField(editable=False, max_length=3)),
                ('invoice_total_snapshot', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('paid_amount_snapshot', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('outstanding_amount_snapshot', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('payment_override', models.BooleanField(default=False, editable=False)),
                ('payment_override_reason', models.TextField(blank=True, editable=False)),
                ('payment_override_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('job_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_release', to='jobs.jobcard')),
                ('payment_override_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_release_payment_overrides', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_releases_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-released_at', '-pk'),
                'permissions': (('release_vehicle', 'Can release a completed vehicle'), ('override_vehicle_release_payment', 'Can release a vehicle with an unpaid balance')),
                'indexes': [models.Index(fields=['released_at', 'job_card'], name='jobs_release_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('invoice_total_snapshot__gte', 0)), name='jobs_release_total_nonnegative'), models.CheckConstraint(condition=models.Q(('paid_amount_snapshot__gte', 0)), name='jobs_release_paid_nonnegative'), models.CheckConstraint(condition=models.Q(('outstanding_amount_snapshot__gte', 0)), name='jobs_release_balance_nonnegative'), models.CheckConstraint(condition=models.Q(('invoice_total_snapshot', django.db.models.expressions.CombinedExpression(models.F('paid_amount_snapshot'), '+', models.F('outstanding_amount_snapshot')))), name='jobs_release_balance_consistent')],
            },
        ),
    ]
