"""Authorization policy for employee roles."""

from apps.accounts.constants import PermissionName, RoleName
from apps.customers.constants import CustomerPermissionName
from apps.jobs.constants import JobPermissionName
from apps.product_catalogue.constants import (
    ProductPermissionName,
)
from apps.quotations.constants import (
    QuotationPermissionName,
)
from apps.service_catalogue.constants import (
    ServicePermissionName,
)
from apps.vehicles.constants import VehiclePermissionName

ROLE_PERMISSION_POLICY: dict[
    RoleName,
    frozenset[str],
] = {
    RoleName.ADMINISTRATOR: frozenset(
        {
            PermissionName.VIEW_USER.value,
            PermissionName.ADD_USER.value,
            PermissionName.CHANGE_USER.value,
            CustomerPermissionName.VIEW_CUSTOMER.value,
            CustomerPermissionName.ADD_CUSTOMER.value,
            CustomerPermissionName.CHANGE_CUSTOMER.value,
            CustomerPermissionName.DEACTIVATE_CUSTOMER.value,
            CustomerPermissionName.REACTIVATE_CUSTOMER.value,
            VehiclePermissionName.VIEW_VEHICLE.value,
            VehiclePermissionName.ADD_VEHICLE.value,
            VehiclePermissionName.CHANGE_VEHICLE.value,
            VehiclePermissionName.TRANSFER_VEHICLE_OWNER.value,
            VehiclePermissionName.DEACTIVATE_VEHICLE.value,
            VehiclePermissionName.REACTIVATE_VEHICLE.value,
            ServicePermissionName.VIEW_SERVICE.value,
            ServicePermissionName.ADD_SERVICE.value,
            ServicePermissionName.CHANGE_SERVICE.value,
            ServicePermissionName.CHANGE_SERVICE_PRICE.value,
            ServicePermissionName.DEACTIVATE_SERVICE.value,
            ServicePermissionName.REACTIVATE_SERVICE.value,
            ProductPermissionName.VIEW_PRODUCT_CATEGORY.value,
            ProductPermissionName.ADD_PRODUCT_CATEGORY.value,
            ProductPermissionName.CHANGE_PRODUCT_CATEGORY.value,
            ProductPermissionName.VIEW_PRODUCT.value,
            ProductPermissionName.ADD_PRODUCT.value,
            ProductPermissionName.CHANGE_PRODUCT.value,
            ProductPermissionName.CHANGE_PRODUCT_PRICE.value,
            ProductPermissionName.DEACTIVATE_PRODUCT.value,
            ProductPermissionName.REACTIVATE_PRODUCT.value,
            JobPermissionName.VIEW_JOB_CARD.value,
            JobPermissionName.ADD_JOB_CARD.value,
            JobPermissionName.CHANGE_JOB_CARD.value,
            JobPermissionName.CANCEL_JOB_CARD.value,
            JobPermissionName.VIEW_INSPECTION.value,
            JobPermissionName.ADD_INSPECTION.value,
            JobPermissionName.VIEW_JOB_NOTE.value,
            JobPermissionName.ADD_JOB_NOTE.value,
            QuotationPermissionName.VIEW_QUOTATION.value,
            QuotationPermissionName.ADD_QUOTATION.value,
            QuotationPermissionName.CHANGE_QUOTATION.value,
            QuotationPermissionName.SUBMIT_QUOTATION.value,
            QuotationPermissionName.APPROVE_QUOTATION.value,
            QuotationPermissionName.REJECT_QUOTATION.value,
            QuotationPermissionName.REVISE_QUOTATION.value,
        }
    ),
    RoleName.RECEPTIONIST: frozenset(
        {
            CustomerPermissionName.VIEW_CUSTOMER.value,
            CustomerPermissionName.ADD_CUSTOMER.value,
            CustomerPermissionName.CHANGE_CUSTOMER.value,
            VehiclePermissionName.VIEW_VEHICLE.value,
            VehiclePermissionName.ADD_VEHICLE.value,
            VehiclePermissionName.CHANGE_VEHICLE.value,
            VehiclePermissionName.TRANSFER_VEHICLE_OWNER.value,
            ServicePermissionName.VIEW_SERVICE.value,
            ProductPermissionName.VIEW_PRODUCT_CATEGORY.value,
            ProductPermissionName.VIEW_PRODUCT.value,
            JobPermissionName.VIEW_JOB_CARD.value,
            JobPermissionName.ADD_JOB_CARD.value,
            JobPermissionName.CHANGE_JOB_CARD.value,
            JobPermissionName.CANCEL_JOB_CARD.value,
            JobPermissionName.VIEW_INSPECTION.value,
            JobPermissionName.VIEW_JOB_NOTE.value,
            JobPermissionName.ADD_JOB_NOTE.value,
            QuotationPermissionName.VIEW_QUOTATION.value,
            QuotationPermissionName.ADD_QUOTATION.value,
            QuotationPermissionName.CHANGE_QUOTATION.value,
            QuotationPermissionName.SUBMIT_QUOTATION.value,
            QuotationPermissionName.APPROVE_QUOTATION.value,
            QuotationPermissionName.REJECT_QUOTATION.value,
            QuotationPermissionName.REVISE_QUOTATION.value,
        }
    ),
    RoleName.SENIOR_TECHNICIAN: frozenset(
        {
            VehiclePermissionName.VIEW_VEHICLE.value,
            ServicePermissionName.VIEW_SERVICE.value,
            ProductPermissionName.VIEW_PRODUCT_CATEGORY.value,
            ProductPermissionName.VIEW_PRODUCT.value,
            JobPermissionName.VIEW_JOB_CARD.value,
            JobPermissionName.VIEW_INSPECTION.value,
            JobPermissionName.ADD_INSPECTION.value,
            JobPermissionName.VIEW_JOB_NOTE.value,
            JobPermissionName.ADD_JOB_NOTE.value,
            QuotationPermissionName.VIEW_QUOTATION.value,
        }
    ),
    RoleName.TECHNICIAN: frozenset(
        {
            VehiclePermissionName.VIEW_VEHICLE.value,
            ServicePermissionName.VIEW_SERVICE.value,
            ProductPermissionName.VIEW_PRODUCT_CATEGORY.value,
            ProductPermissionName.VIEW_PRODUCT.value,
            JobPermissionName.VIEW_JOB_CARD.value,
            JobPermissionName.VIEW_INSPECTION.value,
            JobPermissionName.ADD_INSPECTION.value,
            JobPermissionName.VIEW_JOB_NOTE.value,
            JobPermissionName.ADD_JOB_NOTE.value,
            QuotationPermissionName.VIEW_QUOTATION.value,
        }
    ),
    RoleName.CASHIER: frozenset(
        {
            CustomerPermissionName.VIEW_CUSTOMER.value,
            CustomerPermissionName.ADD_CUSTOMER.value,
            CustomerPermissionName.CHANGE_CUSTOMER.value,
            VehiclePermissionName.VIEW_VEHICLE.value,
            ServicePermissionName.VIEW_SERVICE.value,
            ProductPermissionName.VIEW_PRODUCT_CATEGORY.value,
            ProductPermissionName.VIEW_PRODUCT.value,
            JobPermissionName.VIEW_JOB_CARD.value,
            JobPermissionName.VIEW_INSPECTION.value,
            JobPermissionName.VIEW_JOB_NOTE.value,
            QuotationPermissionName.VIEW_QUOTATION.value,
        }
    ),
    RoleName.MANAGER: frozenset(
        {
            CustomerPermissionName.VIEW_CUSTOMER.value,
            VehiclePermissionName.VIEW_VEHICLE.value,
            ServicePermissionName.VIEW_SERVICE.value,
            ServicePermissionName.ADD_SERVICE.value,
            ServicePermissionName.CHANGE_SERVICE.value,
            ServicePermissionName.CHANGE_SERVICE_PRICE.value,
            ServicePermissionName.DEACTIVATE_SERVICE.value,
            ServicePermissionName.REACTIVATE_SERVICE.value,
            ProductPermissionName.VIEW_PRODUCT_CATEGORY.value,
            ProductPermissionName.ADD_PRODUCT_CATEGORY.value,
            ProductPermissionName.CHANGE_PRODUCT_CATEGORY.value,
            ProductPermissionName.VIEW_PRODUCT.value,
            ProductPermissionName.ADD_PRODUCT.value,
            ProductPermissionName.CHANGE_PRODUCT.value,
            ProductPermissionName.CHANGE_PRODUCT_PRICE.value,
            ProductPermissionName.DEACTIVATE_PRODUCT.value,
            ProductPermissionName.REACTIVATE_PRODUCT.value,
            JobPermissionName.VIEW_JOB_CARD.value,
            JobPermissionName.ADD_JOB_CARD.value,
            JobPermissionName.CHANGE_JOB_CARD.value,
            JobPermissionName.CANCEL_JOB_CARD.value,
            JobPermissionName.VIEW_INSPECTION.value,
            JobPermissionName.ADD_INSPECTION.value,
            JobPermissionName.VIEW_JOB_NOTE.value,
            JobPermissionName.ADD_JOB_NOTE.value,
            QuotationPermissionName.VIEW_QUOTATION.value,
            QuotationPermissionName.ADD_QUOTATION.value,
            QuotationPermissionName.CHANGE_QUOTATION.value,
            QuotationPermissionName.SUBMIT_QUOTATION.value,
            QuotationPermissionName.APPROVE_QUOTATION.value,
            QuotationPermissionName.REJECT_QUOTATION.value,
            QuotationPermissionName.REVISE_QUOTATION.value,
        }
    ),
}
