# Generated by Django 5.2.16 on 2026-07-22 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('registration_number', models.CharField(max_length=30)),
                ('normalized_registration_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('SMALL', 'Small vehicle'), ('COMMERCIAL', 'Commercial vehicle'), ('HEAVY', 'Heavy vehicle')], max_length=20)),
                ('make', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('current_mileage', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('OTHER', 'Other')], max_length=20)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('chassis_number', models.CharField(blank=True, max_length=50)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles_created', to=settings.AUTH_USER_MODEL)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('registration_number', 'vehicle_number'),
                'permissions': (('transfer_vehicle_owner', 'Can transfer vehicle ownership'), ('deactivate_vehicle', 'Can deactivate vehicle'), ('reactivate_vehicle', 'Can reactivate vehicle')),
            },
        ),
        migrations.CreateModel(
            name='VehicleOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_ownership_changes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_ownership_history', to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_history', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('-started_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active', 'registration_number'], name='veh_active_reg_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['current_owner', 'is_active'], name='veh_owner_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleownership',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('vehicle',), name='veh_one_open_owner'),
        ),
    ]
