# Generated by Django 5.2.16 on 2026-07-23 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('normalized_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='product_categories_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40)),
                ('normalized_sku', models.CharField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=80)),
                ('normalized_manufacturer_part_number', models.CharField(blank=True, db_index=True, editable=False, max_length=80)),
                ('unit', models.CharField(choices=[('EACH', 'Each'), ('PAIR', 'Pair'), ('SET', 'Set'), ('BOX', 'Box'), ('LITRE', 'Litre'), ('MILLILITRE', 'Millilitre'), ('KILOGRAM', 'Kilogram'), ('GRAM', 'Gram'), ('METRE', 'Metre')], default='EACH', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_products_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_catalogue.productcategory')),
            ],
            options={
                'ordering': ('name', 'sku'),
                'permissions': (('change_product_price', 'Can change product price'), ('deactivate_product', 'Can deactivate product'), ('reactivate_product', 'Can reactivate product')),
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_price_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='product_catalogue.product')),
            ],
            options={
                'ordering': ('-effective_from', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active', 'name'], name='prodcat_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'name'], name='product_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='product_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_until__isnull', True)), fields=('product',), name='product_one_current_price'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='product_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='product_price_valid_period'),
        ),
    ]
