# Generated by Django 5.2.16 on 2026-08-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'report access',
                'verbose_name_plural': 'report access',
                'permissions': (('access_reports', 'Can access operational reports'), ('view_customer_finance_report', 'Can view the customer finance report'), ('view_workshop_report', 'Can view the workshop operations report'), ('view_inventory_report', 'Can view the inventory report'), ('view_purchasing_report', 'Can view the purchasing report'), ('export_reports', 'Can export operational reports')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
