# Generated by Django 5.2.16 on 2026-07-25 20:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('VOIDED', 'Voided')], db_index=True, default='DRAFT', max_length=30)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('work_order_number_snapshot', models.CharField(editable=False, max_length=30)),
                ('job_number_snapshot', models.CharField(editable=False, max_length=30)),
                ('quotation_number_snapshot', models.CharField(editable=False, max_length=40)),
                ('customer_name_snapshot', models.CharField(editable=False, max_length=200)),
                ('customer_phone_snapshot', models.CharField(blank=True, editable=False, max_length=30)),
                ('customer_email_snapshot', models.EmailField(blank=True, editable=False, max_length=254)),
                ('vehicle_registration_snapshot', models.CharField(editable=False, max_length=40)),
                ('vehicle_make_snapshot', models.CharField(editable=False, max_length=100)),
                ('vehicle_model_snapshot', models.CharField(editable=False, max_length=100)),
                ('vehicle_year_snapshot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('vehicle_color_snapshot', models.CharField(blank=True, editable=False, max_length=50)),
                ('service_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('product_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('issued_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_updated', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_voided', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='workshop.workorder')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'permissions': (('issue_invoice', 'Can issue an invoice'), ('void_invoice', 'Can void an invoice')),
            },
        ),
        migrations.CreateModel(
            name='InvoiceProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('product_sku_snapshot', models.CharField(editable=False, max_length=40)),
                ('product_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('unit_snapshot', models.CharField(editable=False, max_length=20)),
                ('description_snapshot', models.TextField(blank=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_product_lines_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='billing.invoice')),
                ('source_product_requirement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_product_line', to='workshop.workproductrequirement')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('service_code_snapshot', models.CharField(editable=False, max_length=30)),
                ('service_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('description_snapshot', models.TextField(blank=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_service_lines_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='billing.invoice')),
                ('source_work_task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_service_line', to='workshop.worktask')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('VOIDED', 'Voided')], db_index=True, default='POSTED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile money'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank transfer'), ('OTHER', 'Other')], max_length=30)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('received_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-paid_at', '-pk'),
                'permissions': (('record_payment', 'Can record an invoice payment'), ('void_payment', 'Can void an invoice payment')),
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'created_at'], name='bill_invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='bill_invoice_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='bill_invoice_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_percentage__gte', 0), ('tax_percentage__lte', 100)), name='bill_invoice_tax_range'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('service_subtotal__gte', 0)), name='bill_service_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('product_subtotal__gte', 0)), name='bill_product_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='bill_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='bill_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0)), name='bill_taxable_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='bill_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='bill_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceproductline',
            constraint=models.UniqueConstraint(fields=('invoice', 'position'), name='bill_unique_product_position'),
        ),
        migrations.AddConstraint(
            model_name='invoiceproductline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bill_product_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceproductline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='bill_product_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceserviceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'position'), name='bill_unique_service_position'),
        ),
        migrations.AddConstraint(
            model_name='invoiceserviceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bill_service_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceserviceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='bill_service_price_positive'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='bill_payment_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='bill_payment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bill_payment_amount_positive'),
        ),
    ]
