# Generated by Django 5.2.16 on 2026-07-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], max_length=20)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('normalized_phone_number', models.CharField(db_index=True, editable=False, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'customer_number'),
                'permissions': (('deactivate_customer', 'Can deactivate customer'), ('reactivate_customer', 'Can reactivate customer')),
                'indexes': [models.Index(fields=['is_active', 'name'], name='cust_active_name_idx')],
            },
        ),
    ]
