# Generated by Django 5.2.16 on 2026-07-24 09:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('product_catalogue', '0001_initial'),
        ('service_catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('revision_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to customer'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('customer_decision_by_name', models.CharField(blank=True, max_length=150)),
                ('decision_method', models.CharField(blank=True, choices=[('IN_PERSON', 'In person'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SIGNED_DOCUMENT', 'Signed document'), ('OTHER', 'Other')], max_length=30)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
                ('decision_recorded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_decisions_recorded', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='jobs.jobcard')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-revision_number'),
                'permissions': (('submit_quotation', 'Can submit quotation to customer'), ('approve_quotation', 'Can record quotation approval'), ('reject_quotation', 'Can record quotation rejection'), ('revise_quotation', 'Can create quotation revision')),
            },
        ),
        migrations.CreateModel(
            name='QuotationProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('product_sku_snapshot', models.CharField(editable=False, max_length=40)),
                ('product_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('unit_snapshot', models.CharField(editable=False, max_length=20)),
                ('description_snapshot', models.TextField(blank=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_product_lines_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='product_catalogue.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='quotations.quotation')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='QuotationServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('service_code_snapshot', models.CharField(editable=False, max_length=30)),
                ('service_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('description_snapshot', models.TextField(blank=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_service_lines_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='quotations.quotation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='service_catalogue.service')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['job_card', 'status'], name='quote_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['is_current', 'status'], name='quote_current_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('job_card', 'revision_number'), name='quote_unique_job_revision'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('job_card',), name='quote_one_current_per_job'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='quote_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('tax_percentage__gte', 0), ('tax_percentage__lte', 100)), name='quote_tax_range'),
        ),
        migrations.AddConstraint(
            model_name='quotationproductline',
            constraint=models.UniqueConstraint(fields=('quotation', 'product'), name='quote_unique_product_line'),
        ),
        migrations.AddConstraint(
            model_name='quotationproductline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quote_product_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotationproductline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='quote_product_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotationserviceline',
            constraint=models.UniqueConstraint(fields=('quotation', 'service'), name='quote_unique_service_line'),
        ),
        migrations.AddConstraint(
            model_name='quotationserviceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quote_service_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotationserviceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='quote_service_price_positive'),
        ),
    ]
