# Generated by Django 5.2.16 on 2026-07-24 11:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('READY', 'Ready for work'), ('IN_PROGRESS', 'In progress'), ('ON_HOLD', 'On hold'), ('AWAITING_REVIEW', 'Awaiting quality review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('approved_quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='quotations.quotation')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_created', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='jobs.jobcard')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'permissions': (('start_work_order', 'Can start a work order'), ('hold_work_order', 'Can place a work order on hold'), ('resume_work_order', 'Can resume a work order'), ('complete_work_order', 'Can complete a work order')),
            },
        ),
        migrations.CreateModel(
            name='WorkProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('product_sku_snapshot', models.CharField(editable=False, max_length=40)),
                ('product_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('unit_snapshot', models.CharField(editable=False, max_length=20)),
                ('description_snapshot', models.TextField(blank=True, editable=False)),
                ('approved_quantity', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('approved_unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('inventory_status', models.CharField(choices=[('NOT_RESERVED', 'Not reserved'), ('PARTIALLY_RESERVED', 'Partially reserved'), ('RESERVED', 'Reserved'), ('PARTIALLY_ISSUED', 'Partially issued'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_RESERVED', max_length=30)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='work_product_requirements_created', to=settings.AUTH_USER_MODEL)),
                ('source_product_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_requirement', to='quotations.quotationproductline')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_requirements', to='workshop.workorder')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('service_code_snapshot', models.CharField(editable=False, max_length=30)),
                ('service_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('description_snapshot', models.TextField(blank=True, editable=False)),
                ('approved_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), editable=False, max_digits=10)),
                ('approved_unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('AWAITING_REVIEW', 'Awaiting review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_completion_at', models.DateTimeField(blank=True, null=True)),
                ('actual_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actual_completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('blocked_reason', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='work_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('source_service_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_task', to='quotations.quotationserviceline')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_tasks_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workshop.workorder')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'permissions': (('assign_technician', 'Can assign technicians to work tasks'), ('start_work_task', 'Can start a work task'), ('block_work_task', 'Can block a work task'), ('complete_work_task', 'Can complete a work task')),
            },
        ),
        migrations.CreateModel(
            name='TechnicianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('REMOVED', 'Removed')], db_index=True, default='ASSIGNED', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('removed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('removal_reason', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='technician_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_assignments', to=settings.AUTH_USER_MODEL)),
                ('work_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workshop.worktask')),
            ],
            options={
                'ordering': ('-is_active', '-assigned_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='WorkTaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('GENERAL', 'General'), ('TECHNICAL', 'Technical'), ('BLOCKER', 'Blocker'), ('COMPLETION', 'Completion')], default='GENERAL', max_length=20)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='work_task_notes_created', to=settings.AUTH_USER_MODEL)),
                ('work_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='workshop.worktask')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'created_at'], name='work_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workproductrequirement',
            index=models.Index(fields=['work_order', 'inventory_status'], name='work_product_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='workproductrequirement',
            constraint=models.UniqueConstraint(fields=('work_order', 'position'), name='work_unique_product_position'),
        ),
        migrations.AddConstraint(
            model_name='workproductrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('approved_quantity__gt', 0)), name='work_product_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='workproductrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('approved_unit_price__gt', 0)), name='work_product_price_positive'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['work_order', 'status'], name='work_task_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='worktask',
            constraint=models.UniqueConstraint(fields=('work_order', 'position'), name='work_unique_task_position'),
        ),
        migrations.AddConstraint(
            model_name='worktask',
            constraint=models.CheckConstraint(condition=models.Q(('approved_quantity__gt', 0)), name='work_task_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='worktask',
            constraint=models.CheckConstraint(condition=models.Q(('approved_unit_price__gt', 0)), name='work_task_price_positive'),
        ),
        migrations.AddIndex(
            model_name='technicianassignment',
            index=models.Index(fields=['technician', 'is_active'], name='work_assign_tech_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicianassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('work_task', 'technician'), name='work_unique_active_assignment'),
        ),
    ]
