# Generated by Django 5.2.16 on 2026-07-24 21:15

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_catalogue', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('normalized_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_locations_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_locations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='product_catalogue.product')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_updated', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.stocklocation')),
            ],
            options={
                'ordering': ('product__name', 'location__name'),
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIALLY_ISSUED', 'Partially issued'), ('FULFILLED', 'Fulfilled'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=24)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_issued', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('quantity_released', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventoryitem')),
                ('released_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations_released', to=settings.AUTH_USER_MODEL)),
                ('reserved_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations_created', to=settings.AUTH_USER_MODEL)),
                ('work_product_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='workshop.workproductrequirement')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'permissions': (('reserve_stock', 'Can reserve stock'), ('release_stock_reservation', 'Can release a stock reservation')),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Stock receipt'), ('ISSUE', 'Workshop issue'), ('RETURN', 'Workshop return'), ('ADJUSTMENT_IN', 'Positive adjustment'), ('ADJUSTMENT_OUT', 'Negative adjustment')], db_index=True, max_length=24)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem')),
                ('source_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movements', to='inventory.stockmovement')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockreservation')),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'permissions': (('receive_stock', 'Can receive stock'), ('issue_stock', 'Can issue stock'), ('return_stock', 'Can return issued stock'), ('adjust_stock', 'Can adjust stock')),
            },
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['is_active', 'name'], name='inv_loc_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['is_active', 'product'], name='inv_item_active_product_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['location', 'is_active'], name='inv_item_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('product', 'location'), name='inv_unique_product_location'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='inv_reorder_level_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['inventory_item', 'status'], name='inv_res_item_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['work_product_requirement', 'status'], name='inv_res_requirement_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gt', 0)), name='inv_reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_issued__gte', 0)), name='inv_reservation_issued_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_released__gte', 0)), name='inv_reservation_released_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_issued__lte', django.db.models.expressions.CombinedExpression(models.F('quantity_reserved'), '-', models.F('quantity_released')))), name='inv_reservation_within_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('ACTIVE', 'PARTIALLY_ISSUED'))), fields=('inventory_item', 'work_product_requirement'), name='inv_one_active_reservation'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory_item', 'occurred_at'], name='inv_move_item_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'occurred_at'], name='inv_move_type_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inv_movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='inv_movement_cost_nonnegative'),
        ),
    ]
