# Generated by Django 5.2.16 on 2026-07-28 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('code', models.CharField(max_length=30)),
                ('normalized_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('tax_identifier', models.CharField(blank=True, max_length=80)),
                ('payment_terms_days', models.PositiveIntegerField(default=0)),
                ('preferred_currency', models.CharField(default='UGX', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'supplier_number'),
                'permissions': (('deactivate_supplier', 'Can deactivate supplier'), ('reactivate_supplier', 'Can reactivate supplier')),
                'indexes': [models.Index(fields=['is_active', 'name'], name='purch_supplier_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('payment_terms_days__gte', 0)), name='purch_supplier_terms_nonnegative')],
            },
        ),
    ]
