# Generated by Django 5.2.16 on 2026-07-28 06:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('supplier_number_snapshot', models.CharField(editable=False, max_length=20)),
                ('supplier_code_snapshot', models.CharField(editable=False, max_length=30)),
                ('supplier_name_snapshot', models.CharField(editable=False, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for approval'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Fully received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancellation_reason', models.TextField(blank=True, editable=False)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_submitted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.supplier')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'permissions': (('submit_purchase_order', 'Can submit purchase order for approval'), ('approve_purchase_order', 'Can approve purchase order'), ('cancel_purchase_order', 'Can cancel purchase order')),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('product_sku_snapshot', models.CharField(editable=False, max_length=40)),
                ('product_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('unit_snapshot', models.CharField(editable=False, max_length=20)),
                ('description_snapshot', models.TextField(blank=True, editable=False)),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='product_catalogue.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purch_order_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'expected_delivery_date'], name='purch_order_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='purch_order_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('tax_percentage__gte', 0), ('tax_percentage__lte', 100)), name='purch_order_tax_range'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_cost__gte', 0)), name='purch_order_delivery_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='purch_order_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'position'), name='purch_order_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='purch_order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gt', 0)), name='purch_order_unit_cost_positive'),
        ),
    ]
