# Generated by Django 5.2.16 on 2026-07-28 08:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchasing', '0002_purchaseorder_purchaseorderline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods_receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('purchase_order_number_snapshot', models.CharField(editable=False, max_length=30)),
                ('supplier_number_snapshot', models.CharField(editable=False, max_length=20)),
                ('supplier_name_snapshot', models.CharField(editable=False, max_length=200)),
                ('supplier_delivery_reference', models.CharField(blank=True, max_length=120)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchasing.purchaseorder')),
                ('received_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-received_at', '-pk'),
                'permissions': (('receive_purchase_order', 'Can receive an approved purchase order'),),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_sku_snapshot', models.CharField(editable=False, max_length=40)),
                ('product_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('unit_snapshot', models.CharField(editable=False, max_length=20)),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_snapshot', models.CharField(editable=False, max_length=3)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines_created', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.goodsreceipt')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_lines', to='inventory.inventoryitem')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchasing.purchaseorderline')),
                ('stock_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_line', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ('purchase_order_line__position', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['purchase_order', 'received_at'], name='purch_receipt_order_time_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptline',
            index=models.Index(fields=['purchase_order_line', 'created_at'], name='purch_receipt_line_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.UniqueConstraint(fields=('goods_receipt', 'purchase_order_line'), name='purch_receipt_unique_order_line'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gt', 0)), name='purch_receipt_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gt', 0)), name='purch_receipt_cost_positive'),
        ),
    ]
