# Generated by Django 5.2.16 on 2026-07-28 14:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_goodsreceipt_goodsreceiptline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('supplier_reference', models.CharField(max_length=120)),
                ('normalized_supplier_reference', models.CharField(editable=False, max_length=120)),
                ('purchase_order_number_snapshot', models.CharField(editable=False, max_length=30)),
                ('supplier_number_snapshot', models.CharField(editable=False, max_length=20)),
                ('supplier_name_snapshot', models.CharField(editable=False, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('VOIDED', 'Voided')], db_index=True, default='DRAFT', max_length=30)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('invoice_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(db_index=True)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('void_reason', models.TextField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices_posted', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='purchasing.supplier')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices_updated', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-invoice_date', '-pk'),
                'permissions': (('post_supplier_invoice', 'Can post a supplier invoice'), ('void_supplier_invoice', 'Can void a supplier invoice')),
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_sku_snapshot', models.CharField(editable=False, max_length=40)),
                ('product_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('unit_snapshot', models.CharField(editable=False, max_length=20)),
                ('quantity_invoiced', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines_created', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='purchasing.goodsreceiptline')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='purchasing.purchaseorderline')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.supplierinvoice')),
            ],
            options={
                'ordering': ('purchase_order_line__position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile money'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('VOIDED', 'Voided')], db_index=True, default='POSTED', max_length=20)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('void_reason', models.TextField(blank=True, editable=False)),
                ('recorded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.supplierinvoice')),
                ('voided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-paid_at', '-pk'),
                'permissions': (('record_supplier_payment', 'Can record a supplier payment'), ('void_supplier_payment', 'Can void a supplier payment')),
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier', 'status'], name='purch_sinv_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['due_date', 'status'], name='purch_sinv_due_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['purchase_order', 'status'], name='purch_sinv_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'normalized_supplier_reference'), name='purch_sinv_supplier_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('line_subtotal__gte', 0)), name='purch_sinv_subtotal_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='purch_sinv_tax_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('other_charges__gte', 0)), name='purch_sinv_charges_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='purch_sinv_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.UniqueConstraint(fields=('supplier_invoice', 'goods_receipt_line'), name='purch_sinv_line_receipt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_invoiced__gt', 0)), name='purch_sinv_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gt', 0)), name='purch_sinv_line_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='purch_sinv_line_total_nonneg'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier_invoice', 'status'], name='purch_spay_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['paid_at', 'status'], name='purch_spay_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purch_spay_amount_positive'),
        ),
    ]
